version: "3.5"

services:

  config-one:
    image: mongo:4.2
    container_name:  config-one
    command: mongod --configsvr --replSet configRR --port 27019
  config-two:
    image: mongo:4.2
    container_name: config-two
    command: mongod --configsvr --replSet configRR --port 27019
  config-three:
    image: mongo:4.2
    container_name: config-three
    command: mongod --configsvr --replSet configRR --port 27019

  shard-one:
    image: mongo:4.2
    container_name: shard-one
    command: mongod --shardsvr --replSet shardRR --port 27018
  shard-two:
    image: mongo:4.2
    container_name: shard-two
    command: mongod --shardsvr --replSet shardRR --port 27018
  shard-three:
    image: mongo:4.2
    container_name: shard-three
    command: mongod --shardsvr --replSet shardRR --port 27018

  shard-one-one:
    image: mongo:4.2
    container_name: shard-one-one
    command: mongod --shardsvr --replSet shardRR2 --port 27018
  shard-two-two:
    image: mongo:4.2
    container_name: shard-two-two
    command: mongod --shardsvr --replSet shardRR2 --port 27018
  shard-three-three:
    image: mongo:4.2
    container_name: shard-three-three
    command: mongod --shardsvr --replSet shardRR2 --port 27018

  mongos-one:
    image: mongo:4.2
    container_name: mongos-one
    command: mongos --configdb configRR/config-one:27019,config-two:27019,config-three:27019 --port 27017

